server:
  port: 8000
spring:
  profiles:
    active: default
  application:
    name: gateway
  cloud:    gateway:
      discovery:        locator:          enabled: true
          lower-case-service-id: true#      routes:#      - id: service2
#        uri: lb://SERVICE-2
#        predicates:#        - Path=/service-2/**
#        filters:#        - RewritePath=/service-2/(?<path>.*),/$\{path}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://ec2-15-164-230-178.ap-northeast-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: ec2-15-164-230-178.ap-northeast-2.compute.amazonaws.com
